name: monero
description: Dart library for monero
version: 0.0.0
repository: https://git.mrcyjanek.net/mrcyjanek/monero.dart

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.1.0
  ledger_flutter:
    git:
      url: https://github.com/MrCyjaneK/ledger-flutter
      ref: d68f1be485717bedad0779ee6114afec1896fbc9

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  ffigen: ^13.0.0
