name: monero
description: Dart library for monero
version: 0.0.0
repository: https://git.mrcyjanek.net/mrcyjanek/monero.dart

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.1.0
  ledger_flutter_plus:
    git:
      url: https://github.com/cake-tech/ledger-flutter-plus
      ref: cake-v1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  ffigen: ^13.0.0
